import { documentSchema, type Document, type SceneNode } from "./schema"

const createdAt = "2026-08-26T00:00:00.000Z"

const text = (
  id: string,
  name: string,
  value: string,
  x: number,
  y: number,
  width: number,
  height: number,
  fontSize: number,
  color = "#1e2622",
  align: "left" | "center" | "right" = "left"
): SceneNode => ({
  id,
  type: "text",
  name,
  text: value,
  runs: [],
  paragraphs: [],
  links: [],
  x,
  y,
  width,
  height,
  rotation: 0,
  opacity: 1,
  visible: true,
  locked: false,
  color,
  fontFamily: "Geist Variable",
  fontSize,
  fontWeight: fontSize >= 52 ? 600 : 450,
  lineHeight: 1.18,
  letterSpacing: 0,
  align,
  sizingMode: "fixed",
})

const rect = (
  id: string,
  name: string,
  x: number,
  y: number,
  width: number,
  height: number,
  fill: string,
  radius = 0
): SceneNode => ({
  id,
  type: "rect",
  name,
  x,
  y,
  width,
  height,
  rotation: 0,
  opacity: 1,
  visible: true,
  locked: false,
  fill,
  radius,
  strokeWidth: 0,
})

const nodes: SceneNode[] = [
  rect("cover-panel", "Olive panel", 610, 0, 630, 1754, "#233128"),
  text(
    "cover-eyebrow",
    "Document type",
    "WEDDING PHOTOGRAPHY PROPOSAL",
    86,
    112,
    470,
    40,
    19,
    "#5f6f66"
  ),
  text("cover-title", "Couple names", "Aditi & Kabir", 82, 545, 485, 180, 74),
  text(
    "cover-date",
    "Event date",
    "18 January 2027 · Jaipur",
    86,
    760,
    460,
    50,
    24,
    "#5f6f66"
  ),
  text(
    "cover-studio",
    "Studio name",
    "Northstar Weddings",
    692,
    1510,
    430,
    50,
    24,
    "#f7f2e8"
  ),

  text(
    "story-kicker",
    "Story kicker",
    "01 · YOUR STORY",
    80,
    96,
    500,
    40,
    19,
    "#5f6f66"
  ),
  text(
    "story-title",
    "Story title",
    "A weekend that feels like you",
    80,
    290,
    940,
    150,
    62
  ),
  text(
    "story-copy",
    "Story copy",
    "Three days, two families, one unhurried visual story. We will build the coverage around candid moments, clean portraits, and the details you spent months choosing.",
    80,
    510,
    880,
    260,
    30,
    "#455049"
  ),
  rect("story-note", "Story note", 80, 1130, 1080, 340, "#e9e2d4", 28),
  text(
    "story-note-copy",
    "Story note copy",
    "The proposal stays editable. Every accepted update also changes the matching package card and follow-up card.",
    132,
    1215,
    960,
    180,
    29
  ),

  text(
    "package-kicker",
    "Package kicker",
    "02 · RECOMMENDED PACKAGE",
    80,
    96,
    600,
    40,
    19,
    "#5f6f66"
  ),
  text(
    "package-name",
    "Package name",
    "The Heirloom Weekend",
    80,
    260,
    850,
    90,
    58
  ),
  text(
    "package-price",
    "Package price",
    "₹3,85,000",
    80,
    400,
    600,
    90,
    50,
    "#8a5d38"
  ),
  rect("package-list", "Package list panel", 80, 590, 1080, 760, "#f3efe7", 28),
  text(
    "package-list-copy",
    "Package contents",
    "• Three-day photography coverage\n• Two lead photographers\n• One cinematic film and three reels\n• 60-page fine-art album\n• Private online gallery",
    132,
    665,
    940,
    560,
    31
  ),
  text(
    "package-validity",
    "Offer validity",
    "Proposal valid until 30 September 2026",
    84,
    1450,
    700,
    50,
    22,
    "#5f6f66"
  ),

  text(
    "timeline-kicker",
    "Timeline kicker",
    "03 · COVERAGE PLAN",
    80,
    96,
    500,
    40,
    19,
    "#5f6f66"
  ),
  text(
    "timeline-title",
    "Timeline title",
    "Present for the loud parts. Ready for the quiet ones.",
    80,
    250,
    970,
    160,
    58
  ),
  rect("timeline-line", "Timeline line", 136, 555, 5, 730, "#c7b69f", 3),
  text(
    "timeline-items",
    "Timeline items",
    "DAY ONE  ·  Welcome dinner and family portraits\n\nDAY TWO  ·  Haldi, mehendi, and evening celebration\n\nDAY THREE  ·  Ceremony, portraits, and reception",
    190,
    535,
    820,
    700,
    30
  ),

  text(
    "terms-kicker",
    "Terms kicker",
    "04 · NEXT STEPS",
    80,
    96,
    500,
    40,
    19,
    "#5f6f66"
  ),
  text(
    "terms-title",
    "Terms title",
    "A clear path from proposal to confirmation",
    80,
    260,
    900,
    145,
    58
  ),
  text(
    "terms-copy",
    "Terms copy",
    "1. Review the coverage and deliverables\n\n2. Request any changes in one reply\n\n3. Approve the final quotation\n\n4. Sign and pay the booking retainer",
    80,
    535,
    850,
    620,
    32
  ),
  rect("terms-contact", "Contact panel", 80, 1300, 1080, 260, "#233128", 28),
  text(
    "terms-contact-copy",
    "Contact copy",
    "hello@northstar.example  ·  +91 90000 00000",
    132,
    1403,
    900,
    50,
    25,
    "#f7f2e8"
  ),

  rect("wa-background", "WhatsApp background", 0, 0, 1080, 1350, "#233128"),
  text(
    "wa-studio",
    "WhatsApp studio",
    "NORTHSTAR WEDDINGS",
    72,
    70,
    700,
    40,
    20,
    "#ddd2bf"
  ),
  text(
    "wa-title",
    "WhatsApp package name",
    "The Heirloom Weekend",
    72,
    245,
    900,
    140,
    62,
    "#f7f2e8"
  ),
  text(
    "wa-price",
    "WhatsApp price",
    "₹3,85,000",
    72,
    430,
    700,
    90,
    48,
    "#d7a879"
  ),
  rect("wa-card", "WhatsApp details card", 72, 630, 936, 535, "#f7f2e8", 30),
  text(
    "wa-copy",
    "WhatsApp details",
    "3 days · 2 photographers\nFilm + 3 reels · Fine-art album\nPrivate gallery",
    128,
    730,
    800,
    260,
    34
  ),
  text(
    "wa-validity",
    "WhatsApp validity",
    "Valid until 30 September 2026",
    128,
    1060,
    720,
    45,
    22,
    "#5f6f66"
  ),

  rect("square-background", "Square background", 0, 0, 1080, 1080, "#e9e2d4"),
  text(
    "square-eyebrow",
    "Square eyebrow",
    "YOUR PROPOSAL IS READY",
    72,
    74,
    800,
    40,
    20,
    "#5f6f66"
  ),
  text(
    "square-title",
    "Square couple names",
    "Aditi & Kabir",
    72,
    345,
    900,
    135,
    70
  ),
  text(
    "square-copy",
    "Square follow-up",
    "A five-page plan for your Jaipur celebration, ready for your notes.",
    72,
    545,
    830,
    150,
    31,
    "#455049"
  ),
  rect("square-cta", "Square CTA", 72, 842, 450, 104, "#233128", 52),
  text(
    "square-cta-copy",
    "Square CTA copy",
    "Review proposal",
    112,
    872,
    365,
    45,
    25,
    "#f7f2e8",
    "center"
  ),
]

export const northstarSeed: Document = documentSchema.parse({
  schemaVersion: 3,
  id: "doc-northstar-aditi-kabir",
  name: "Aditi & Kabir proposal pack",
  revision: 3,
  createdAt,
  updatedAt: createdAt,
  outputs: [
    {
      id: "proposal",
      name: "Five-page proposal",
      kind: "proposal",
      pageIds: ["cover", "story", "package", "timeline", "terms"],
      exportFormats: ["pdf", "png"],
    },
    {
      id: "whatsapp",
      name: "WhatsApp package card",
      kind: "whatsapp_portrait",
      pageIds: ["whatsapp-card"],
      exportFormats: ["png"],
    },
    {
      id: "follow-up",
      name: "Square follow-up card",
      kind: "square",
      pageIds: ["square-card"],
      exportFormats: ["png"],
    },
  ],
  pages: [
    {
      id: "cover",
      outputId: "proposal",
      name: "Cover",
      width: 1240,
      height: 1754,
      background: "#f7f2e8",
      nodeIds: [
        "cover-panel",
        "cover-eyebrow",
        "cover-title",
        "cover-date",
        "cover-studio",
      ],
    },
    {
      id: "story",
      outputId: "proposal",
      name: "Story",
      width: 1240,
      height: 1754,
      background: "#f7f2e8",
      nodeIds: [
        "story-kicker",
        "story-title",
        "story-copy",
        "story-note",
        "story-note-copy",
      ],
    },
    {
      id: "package",
      outputId: "proposal",
      name: "Package",
      width: 1240,
      height: 1754,
      background: "#f7f2e8",
      nodeIds: [
        "package-kicker",
        "package-name",
        "package-price",
        "package-list",
        "package-list-copy",
        "package-validity",
      ],
    },
    {
      id: "timeline",
      outputId: "proposal",
      name: "Coverage",
      width: 1240,
      height: 1754,
      background: "#f7f2e8",
      nodeIds: [
        "timeline-kicker",
        "timeline-title",
        "timeline-line",
        "timeline-items",
      ],
    },
    {
      id: "terms",
      outputId: "proposal",
      name: "Next steps",
      width: 1240,
      height: 1754,
      background: "#f7f2e8",
      nodeIds: [
        "terms-kicker",
        "terms-title",
        "terms-copy",
        "terms-contact",
        "terms-contact-copy",
      ],
    },
    {
      id: "whatsapp-card",
      outputId: "whatsapp",
      name: "Package card",
      width: 1080,
      height: 1350,
      background: "#233128",
      nodeIds: [
        "wa-background",
        "wa-studio",
        "wa-title",
        "wa-price",
        "wa-card",
        "wa-copy",
        "wa-validity",
      ],
    },
    {
      id: "square-card",
      outputId: "follow-up",
      name: "Follow-up",
      width: 1080,
      height: 1080,
      background: "#e9e2d4",
      nodeIds: [
        "square-background",
        "square-eyebrow",
        "square-title",
        "square-copy",
        "square-cta",
        "square-cta-copy",
      ],
    },
  ],
  nodes,
  typographyStyles: [],
  paintStyles: [],
  variables: [],
  fields: [
    {
      id: "couple_names",
      key: "couple_names",
      label: "Couple names",
      type: "text",
      required: true,
      defaultValue: "Aditi & Kabir",
    },
    {
      id: "event_date",
      key: "event_date",
      label: "Event date and place",
      type: "text",
      required: true,
      defaultValue: "18 January 2027 · Jaipur",
    },
    {
      id: "package_name",
      key: "package_name",
      label: "Package name",
      type: "text",
      required: true,
      defaultValue: "The Heirloom Weekend",
    },
    {
      id: "package_price",
      key: "package_price",
      label: "Package price",
      type: "currency",
      required: true,
      defaultValue: "385000",
    },
    {
      id: "valid_until",
      key: "valid_until",
      label: "Valid until",
      type: "text",
      required: true,
      defaultValue: "30 September 2026",
    },
  ],
  fieldValues: {
    couple_names: "Aditi & Kabir",
    event_date: "18 January 2027 · Jaipur",
    package_name: "The Heirloom Weekend",
    package_price: "385000",
    valid_until: "30 September 2026",
  },
  bindings: [
    {
      id: "bind-cover-couple",
      fieldId: "couple_names",
      nodeId: "cover-title",
      property: "text",
    },
    {
      id: "bind-square-couple",
      fieldId: "couple_names",
      nodeId: "square-title",
      property: "text",
    },
    {
      id: "bind-cover-date",
      fieldId: "event_date",
      nodeId: "cover-date",
      property: "text",
    },
    {
      id: "bind-package-name",
      fieldId: "package_name",
      nodeId: "package-name",
      property: "text",
    },
    {
      id: "bind-wa-name",
      fieldId: "package_name",
      nodeId: "wa-title",
      property: "text",
    },
    {
      id: "bind-package-price",
      fieldId: "package_price",
      nodeId: "package-price",
      property: "text",
    },
    {
      id: "bind-wa-price",
      fieldId: "package_price",
      nodeId: "wa-price",
      property: "text",
    },
  ],
})
