/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteRouteImport } from './routes/_studio/route'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as RenderConformanceRouteImport } from './routes/render-conformance'
import { Route as StudioIndexRouteImport } from './routes/_studio/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as StudioCompositionHandoffsTokenRouteImport } from './routes/_studio/composition-handoffs/$token'
import { Route as StudioDocumentsDocumentIdRouteImport } from './routes/_studio/documents/$documentId'
import { Route as V1IntegrationsCompositionHandoffsRouteImport } from './routes/v1/integrations/composition-handoffs'
import { Route as V1RendersRenderIdRouteImport } from './routes/v1/renders/$renderId'
import { Route as V1StudioExportPdfRouteImport } from './routes/v1/studio/export-pdf'
import { Route as V1StudioExportPngRouteImport } from './routes/v1/studio/export-png'
import { Route as V1StudioPageThumbnailRouteImport } from './routes/v1/studio/page-thumbnail'
import { Route as V1StudioQuotationCompositionsRouteImport } from './routes/v1/studio/quotation-compositions'
import { Route as V1StudioRenderRouteImport } from './routes/v1/studio/render'
import { Route as V1StudioAssetsIndexRouteImport } from './routes/v1/studio/assets/index'
import { Route as V1StudioAssetsAssetIdRouteImport } from './routes/v1/studio/assets/$assetId'
import { Route as V1StudioCompositionHandoffsTokenRouteImport } from './routes/v1/studio/composition-handoffs/$token'
import { Route as V1StudioFigmaHandoffsIndexRouteImport } from './routes/v1/studio/figma-handoffs/index'
import { Route as V1StudioFigmaHandoffsTokenRouteImport } from './routes/v1/studio/figma-handoffs/$token'
import { Route as V1StudioLibraryPreferencesRouteImport } from './routes/v1/studio/library/preferences'
import { Route as V1StudioMediaDerivationsJobIdRouteImport } from './routes/v1/studio/media-derivations/$jobId'
import { Route as V1StudioMediaDerivationsPolicyRouteImport } from './routes/v1/studio/media-derivations/policy'
import { Route as V1StudioRendersIndexRouteImport } from './routes/v1/studio/renders/index'
import { Route as V1StudioSessionDemoRouteImport } from './routes/v1/studio/session/demo'
import { Route as V1StudioSessionResetRouteImport } from './routes/v1/studio/session/reset'
import { Route as V1StudioSessionTokenRouteImport } from './routes/v1/studio/session/token'
import { Route as V1StudioTemplatesIndexRouteImport } from './routes/v1/studio/templates/index'
import { Route as V1StudioTemplatesTemplateIdRouteImport } from './routes/v1/studio/templates/$templateId'
import { Route as V1RendersRenderIdOutputsOutputIdRouteImport } from './routes/v1/renders/$renderId/outputs/$outputId'
import { Route as V1StudioAssetsAssetIdContentRouteImport } from './routes/v1/studio/assets/$assetId/content'
import { Route as V1StudioAssetsAssetIdDeletionImpactRouteImport } from './routes/v1/studio/assets/$assetId/deletion-impact'
import { Route as V1StudioAssetsAssetIdDerivationProvenanceRouteImport } from './routes/v1/studio/assets/$assetId/derivation-provenance'
import { Route as V1StudioAssetsAssetIdDerivationsRouteImport } from './routes/v1/studio/assets/$assetId/derivations'
import { Route as V1StudioAssetsAssetIdUsedRouteImport } from './routes/v1/studio/assets/$assetId/used'
import { Route as V1StudioAssetsLocalPromotionsIndexRouteImport } from './routes/v1/studio/assets/local-promotions/index'
import { Route as V1StudioAssetsLocalPromotionsLocalAssetIdRouteImport } from './routes/v1/studio/assets/local-promotions/$localAssetId'
import { Route as V1StudioAssetsLocalPromotionsResolveRouteImport } from './routes/v1/studio/assets/local-promotions/resolve'
import { Route as V1StudioAssetsUploadReservationsIndexRouteImport } from './routes/v1/studio/assets/upload-reservations/index'
import { Route as V1StudioAssetsUploadReservationsReservationIdRouteImport } from './routes/v1/studio/assets/upload-reservations/$reservationId'
import { Route as V1StudioLibraryCollectionsIndexRouteImport } from './routes/v1/studio/library/collections/index'
import { Route as V1StudioLibraryCollectionsCollectionIdRouteImport } from './routes/v1/studio/library/collections/$collectionId'
import { Route as V1StudioLibraryItemsIndexRouteImport } from './routes/v1/studio/library/items/index'
import { Route as V1StudioMediaDerivationsJobIdCancelRouteImport } from './routes/v1/studio/media-derivations/$jobId/cancel'
import { Route as V1StudioMediaDerivationsJobIdRetryRouteImport } from './routes/v1/studio/media-derivations/$jobId/retry'
import { Route as V1StudioDocumentsDocumentIdRevisionsSnapshotIdRouteImport } from './routes/v1/studio/documents/$documentId/revisions/$snapshotId'
import { Route as V1StudioLibraryCollectionsCollectionIdOrderRouteImport } from './routes/v1/studio/library/collections/$collectionId/order'
import { Route as V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteImport } from './routes/v1/studio/library/items/$itemKind/$itemId/versions/$version'
import { Route as V1StudioLibraryMediaAssetIdVersionsVersionContentRouteImport } from './routes/v1/studio/library/media/$assetId/versions/$version/content'
import { Route as V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRouteImport } from './routes/v1/studio/library/items/$itemKind/$itemId/versions/$version.favorite'
import { Route as V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRouteImport } from './routes/v1/studio/library/items/$itemKind/$itemId/versions/$version.used'
import { Route as V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRouteImport } from './routes/v1/studio/library/collections/$collectionId/items/$itemKind/$itemId/versions/$version'

const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderConformanceRoute = RenderConformanceRouteImport.update({
  id: '/render-conformance',
  path: '/render-conformance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioCompositionHandoffsTokenRoute =
  StudioCompositionHandoffsTokenRouteImport.update({
    id: '/composition-handoffs/$token',
    path: '/composition-handoffs/$token',
    getParentRoute: () => StudioRouteRoute,
  } as any)
const StudioDocumentsDocumentIdRoute =
  StudioDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => StudioRouteRoute,
  } as any)
const V1IntegrationsCompositionHandoffsRoute =
  V1IntegrationsCompositionHandoffsRouteImport.update({
    id: '/v1/integrations/composition-handoffs',
    path: '/v1/integrations/composition-handoffs',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1RendersRenderIdRoute = V1RendersRenderIdRouteImport.update({
  id: '/v1/renders/$renderId',
  path: '/v1/renders/$renderId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioExportPdfRoute = V1StudioExportPdfRouteImport.update({
  id: '/v1/studio/export-pdf',
  path: '/v1/studio/export-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioExportPngRoute = V1StudioExportPngRouteImport.update({
  id: '/v1/studio/export-png',
  path: '/v1/studio/export-png',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioPageThumbnailRoute = V1StudioPageThumbnailRouteImport.update({
  id: '/v1/studio/page-thumbnail',
  path: '/v1/studio/page-thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioQuotationCompositionsRoute =
  V1StudioQuotationCompositionsRouteImport.update({
    id: '/v1/studio/quotation-compositions',
    path: '/v1/studio/quotation-compositions',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioRenderRoute = V1StudioRenderRouteImport.update({
  id: '/v1/studio/render',
  path: '/v1/studio/render',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioAssetsIndexRoute = V1StudioAssetsIndexRouteImport.update({
  id: '/v1/studio/assets/',
  path: '/v1/studio/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioAssetsAssetIdRoute = V1StudioAssetsAssetIdRouteImport.update({
  id: '/v1/studio/assets/$assetId',
  path: '/v1/studio/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioCompositionHandoffsTokenRoute =
  V1StudioCompositionHandoffsTokenRouteImport.update({
    id: '/v1/studio/composition-handoffs/$token',
    path: '/v1/studio/composition-handoffs/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioFigmaHandoffsIndexRoute =
  V1StudioFigmaHandoffsIndexRouteImport.update({
    id: '/v1/studio/figma-handoffs/',
    path: '/v1/studio/figma-handoffs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioFigmaHandoffsTokenRoute =
  V1StudioFigmaHandoffsTokenRouteImport.update({
    id: '/v1/studio/figma-handoffs/$token',
    path: '/v1/studio/figma-handoffs/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioLibraryPreferencesRoute =
  V1StudioLibraryPreferencesRouteImport.update({
    id: '/v1/studio/library/preferences',
    path: '/v1/studio/library/preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioMediaDerivationsJobIdRoute =
  V1StudioMediaDerivationsJobIdRouteImport.update({
    id: '/v1/studio/media-derivations/$jobId',
    path: '/v1/studio/media-derivations/$jobId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioMediaDerivationsPolicyRoute =
  V1StudioMediaDerivationsPolicyRouteImport.update({
    id: '/v1/studio/media-derivations/policy',
    path: '/v1/studio/media-derivations/policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioRendersIndexRoute = V1StudioRendersIndexRouteImport.update({
  id: '/v1/studio/renders/',
  path: '/v1/studio/renders/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioSessionDemoRoute = V1StudioSessionDemoRouteImport.update({
  id: '/v1/studio/session/demo',
  path: '/v1/studio/session/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioSessionResetRoute = V1StudioSessionResetRouteImport.update({
  id: '/v1/studio/session/reset',
  path: '/v1/studio/session/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioSessionTokenRoute = V1StudioSessionTokenRouteImport.update({
  id: '/v1/studio/session/token',
  path: '/v1/studio/session/token',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioTemplatesIndexRoute = V1StudioTemplatesIndexRouteImport.update({
  id: '/v1/studio/templates/',
  path: '/v1/studio/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioTemplatesTemplateIdRoute =
  V1StudioTemplatesTemplateIdRouteImport.update({
    id: '/v1/studio/templates/$templateId',
    path: '/v1/studio/templates/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1RendersRenderIdOutputsOutputIdRoute =
  V1RendersRenderIdOutputsOutputIdRouteImport.update({
    id: '/outputs/$outputId',
    path: '/outputs/$outputId',
    getParentRoute: () => V1RendersRenderIdRoute,
  } as any)
const V1StudioAssetsAssetIdContentRoute =
  V1StudioAssetsAssetIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => V1StudioAssetsAssetIdRoute,
  } as any)
const V1StudioAssetsAssetIdDeletionImpactRoute =
  V1StudioAssetsAssetIdDeletionImpactRouteImport.update({
    id: '/deletion-impact',
    path: '/deletion-impact',
    getParentRoute: () => V1StudioAssetsAssetIdRoute,
  } as any)
const V1StudioAssetsAssetIdDerivationProvenanceRoute =
  V1StudioAssetsAssetIdDerivationProvenanceRouteImport.update({
    id: '/derivation-provenance',
    path: '/derivation-provenance',
    getParentRoute: () => V1StudioAssetsAssetIdRoute,
  } as any)
const V1StudioAssetsAssetIdDerivationsRoute =
  V1StudioAssetsAssetIdDerivationsRouteImport.update({
    id: '/derivations',
    path: '/derivations',
    getParentRoute: () => V1StudioAssetsAssetIdRoute,
  } as any)
const V1StudioAssetsAssetIdUsedRoute =
  V1StudioAssetsAssetIdUsedRouteImport.update({
    id: '/used',
    path: '/used',
    getParentRoute: () => V1StudioAssetsAssetIdRoute,
  } as any)
const V1StudioAssetsLocalPromotionsIndexRoute =
  V1StudioAssetsLocalPromotionsIndexRouteImport.update({
    id: '/v1/studio/assets/local-promotions/',
    path: '/v1/studio/assets/local-promotions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioAssetsLocalPromotionsLocalAssetIdRoute =
  V1StudioAssetsLocalPromotionsLocalAssetIdRouteImport.update({
    id: '/v1/studio/assets/local-promotions/$localAssetId',
    path: '/v1/studio/assets/local-promotions/$localAssetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioAssetsLocalPromotionsResolveRoute =
  V1StudioAssetsLocalPromotionsResolveRouteImport.update({
    id: '/v1/studio/assets/local-promotions/resolve',
    path: '/v1/studio/assets/local-promotions/resolve',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioAssetsUploadReservationsIndexRoute =
  V1StudioAssetsUploadReservationsIndexRouteImport.update({
    id: '/v1/studio/assets/upload-reservations/',
    path: '/v1/studio/assets/upload-reservations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioAssetsUploadReservationsReservationIdRoute =
  V1StudioAssetsUploadReservationsReservationIdRouteImport.update({
    id: '/v1/studio/assets/upload-reservations/$reservationId',
    path: '/v1/studio/assets/upload-reservations/$reservationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioLibraryCollectionsIndexRoute =
  V1StudioLibraryCollectionsIndexRouteImport.update({
    id: '/v1/studio/library/collections/',
    path: '/v1/studio/library/collections/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioLibraryCollectionsCollectionIdRoute =
  V1StudioLibraryCollectionsCollectionIdRouteImport.update({
    id: '/v1/studio/library/collections/$collectionId',
    path: '/v1/studio/library/collections/$collectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioLibraryItemsIndexRoute =
  V1StudioLibraryItemsIndexRouteImport.update({
    id: '/v1/studio/library/items/',
    path: '/v1/studio/library/items/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioMediaDerivationsJobIdCancelRoute =
  V1StudioMediaDerivationsJobIdCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => V1StudioMediaDerivationsJobIdRoute,
  } as any)
const V1StudioMediaDerivationsJobIdRetryRoute =
  V1StudioMediaDerivationsJobIdRetryRouteImport.update({
    id: '/retry',
    path: '/retry',
    getParentRoute: () => V1StudioMediaDerivationsJobIdRoute,
  } as any)
const V1StudioDocumentsDocumentIdRevisionsSnapshotIdRoute =
  V1StudioDocumentsDocumentIdRevisionsSnapshotIdRouteImport.update({
    id: '/v1/studio/documents/$documentId/revisions/$snapshotId',
    path: '/v1/studio/documents/$documentId/revisions/$snapshotId',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioLibraryCollectionsCollectionIdOrderRoute =
  V1StudioLibraryCollectionsCollectionIdOrderRouteImport.update({
    id: '/order',
    path: '/order',
    getParentRoute: () => V1StudioLibraryCollectionsCollectionIdRoute,
  } as any)
const V1StudioLibraryItemsItemKindItemIdVersionsVersionRoute =
  V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteImport.update({
    id: '/v1/studio/library/items/$itemKind/$itemId/versions/$version',
    path: '/v1/studio/library/items/$itemKind/$itemId/versions/$version',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioLibraryMediaAssetIdVersionsVersionContentRoute =
  V1StudioLibraryMediaAssetIdVersionsVersionContentRouteImport.update({
    id: '/v1/studio/library/media/$assetId/versions/$version/content',
    path: '/v1/studio/library/media/$assetId/versions/$version/content',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRoute =
  V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRouteImport.update({
    id: '/favorite',
    path: '/favorite',
    getParentRoute: () =>
      V1StudioLibraryItemsItemKindItemIdVersionsVersionRoute,
  } as any)
const V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRoute =
  V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRouteImport.update({
    id: '/used',
    path: '/used',
    getParentRoute: () =>
      V1StudioLibraryItemsItemKindItemIdVersionsVersionRoute,
  } as any)
const V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRoute =
  V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRouteImport.update(
    {
      id: '/items/$itemKind/$itemId/versions/$version',
      path: '/items/$itemKind/$itemId/versions/$version',
      getParentRoute: () => V1StudioLibraryCollectionsCollectionIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof StudioIndexRoute
  '/demo': typeof DemoRoute
  '/render-conformance': typeof RenderConformanceRoute
  '/api/health': typeof ApiHealthRoute
  '/composition-handoffs/$token': typeof StudioCompositionHandoffsTokenRoute
  '/documents/$documentId': typeof StudioDocumentsDocumentIdRoute
  '/v1/integrations/composition-handoffs': typeof V1IntegrationsCompositionHandoffsRoute
  '/v1/renders/$renderId': typeof V1RendersRenderIdRouteWithChildren
  '/v1/studio/export-pdf': typeof V1StudioExportPdfRoute
  '/v1/studio/export-png': typeof V1StudioExportPngRoute
  '/v1/studio/page-thumbnail': typeof V1StudioPageThumbnailRoute
  '/v1/studio/quotation-compositions': typeof V1StudioQuotationCompositionsRoute
  '/v1/studio/render': typeof V1StudioRenderRoute
  '/v1/studio/assets/$assetId': typeof V1StudioAssetsAssetIdRouteWithChildren
  '/v1/studio/composition-handoffs/$token': typeof V1StudioCompositionHandoffsTokenRoute
  '/v1/studio/figma-handoffs/$token': typeof V1StudioFigmaHandoffsTokenRoute
  '/v1/studio/library/preferences': typeof V1StudioLibraryPreferencesRoute
  '/v1/studio/media-derivations/$jobId': typeof V1StudioMediaDerivationsJobIdRouteWithChildren
  '/v1/studio/media-derivations/policy': typeof V1StudioMediaDerivationsPolicyRoute
  '/v1/studio/session/demo': typeof V1StudioSessionDemoRoute
  '/v1/studio/session/reset': typeof V1StudioSessionResetRoute
  '/v1/studio/session/token': typeof V1StudioSessionTokenRoute
  '/v1/studio/templates/$templateId': typeof V1StudioTemplatesTemplateIdRoute
  '/v1/studio/assets/': typeof V1StudioAssetsIndexRoute
  '/v1/studio/figma-handoffs/': typeof V1StudioFigmaHandoffsIndexRoute
  '/v1/studio/renders/': typeof V1StudioRendersIndexRoute
  '/v1/studio/templates/': typeof V1StudioTemplatesIndexRoute
  '/v1/renders/$renderId/outputs/$outputId': typeof V1RendersRenderIdOutputsOutputIdRoute
  '/v1/studio/assets/$assetId/content': typeof V1StudioAssetsAssetIdContentRoute
  '/v1/studio/assets/$assetId/deletion-impact': typeof V1StudioAssetsAssetIdDeletionImpactRoute
  '/v1/studio/assets/$assetId/derivation-provenance': typeof V1StudioAssetsAssetIdDerivationProvenanceRoute
  '/v1/studio/assets/$assetId/derivations': typeof V1StudioAssetsAssetIdDerivationsRoute
  '/v1/studio/assets/$assetId/used': typeof V1StudioAssetsAssetIdUsedRoute
  '/v1/studio/assets/local-promotions/$localAssetId': typeof V1StudioAssetsLocalPromotionsLocalAssetIdRoute
  '/v1/studio/assets/local-promotions/resolve': typeof V1StudioAssetsLocalPromotionsResolveRoute
  '/v1/studio/assets/upload-reservations/$reservationId': typeof V1StudioAssetsUploadReservationsReservationIdRoute
  '/v1/studio/library/collections/$collectionId': typeof V1StudioLibraryCollectionsCollectionIdRouteWithChildren
  '/v1/studio/media-derivations/$jobId/cancel': typeof V1StudioMediaDerivationsJobIdCancelRoute
  '/v1/studio/media-derivations/$jobId/retry': typeof V1StudioMediaDerivationsJobIdRetryRoute
  '/v1/studio/assets/local-promotions/': typeof V1StudioAssetsLocalPromotionsIndexRoute
  '/v1/studio/assets/upload-reservations/': typeof V1StudioAssetsUploadReservationsIndexRoute
  '/v1/studio/library/collections/': typeof V1StudioLibraryCollectionsIndexRoute
  '/v1/studio/library/items/': typeof V1StudioLibraryItemsIndexRoute
  '/v1/studio/documents/$documentId/revisions/$snapshotId': typeof V1StudioDocumentsDocumentIdRevisionsSnapshotIdRoute
  '/v1/studio/library/collections/$collectionId/order': typeof V1StudioLibraryCollectionsCollectionIdOrderRoute
  '/v1/studio/library/items/$itemKind/$itemId/versions/$version': typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteWithChildren
  '/v1/studio/library/media/$assetId/versions/$version/content': typeof V1StudioLibraryMediaAssetIdVersionsVersionContentRoute
  '/v1/studio/library/items/$itemKind/$itemId/versions/$version/favorite': typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRoute
  '/v1/studio/library/items/$itemKind/$itemId/versions/$version/used': typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRoute
  '/v1/studio/library/collections/$collectionId/items/$itemKind/$itemId/versions/$version': typeof V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRoute
}
export interface FileRoutesByTo {
  '/demo': typeof DemoRoute
  '/render-conformance': typeof RenderConformanceRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof StudioIndexRoute
  '/composition-handoffs/$token': typeof StudioCompositionHandoffsTokenRoute
  '/documents/$documentId': typeof StudioDocumentsDocumentIdRoute
  '/v1/integrations/composition-handoffs': typeof V1IntegrationsCompositionHandoffsRoute
  '/v1/renders/$renderId': typeof V1RendersRenderIdRouteWithChildren
  '/v1/studio/export-pdf': typeof V1StudioExportPdfRoute
  '/v1/studio/export-png': typeof V1StudioExportPngRoute
  '/v1/studio/page-thumbnail': typeof V1StudioPageThumbnailRoute
  '/v1/studio/quotation-compositions': typeof V1StudioQuotationCompositionsRoute
  '/v1/studio/render': typeof V1StudioRenderRoute
  '/v1/studio/assets/$assetId': typeof V1StudioAssetsAssetIdRouteWithChildren
  '/v1/studio/composition-handoffs/$token': typeof V1StudioCompositionHandoffsTokenRoute
  '/v1/studio/figma-handoffs/$token': typeof V1StudioFigmaHandoffsTokenRoute
  '/v1/studio/library/preferences': typeof V1StudioLibraryPreferencesRoute
  '/v1/studio/media-derivations/$jobId': typeof V1StudioMediaDerivationsJobIdRouteWithChildren
  '/v1/studio/media-derivations/policy': typeof V1StudioMediaDerivationsPolicyRoute
  '/v1/studio/session/demo': typeof V1StudioSessionDemoRoute
  '/v1/studio/session/reset': typeof V1StudioSessionResetRoute
  '/v1/studio/session/token': typeof V1StudioSessionTokenRoute
  '/v1/studio/templates/$templateId': typeof V1StudioTemplatesTemplateIdRoute
  '/v1/studio/assets': typeof V1StudioAssetsIndexRoute
  '/v1/studio/figma-handoffs': typeof V1StudioFigmaHandoffsIndexRoute
  '/v1/studio/renders': typeof V1StudioRendersIndexRoute
  '/v1/studio/templates': typeof V1StudioTemplatesIndexRoute
  '/v1/renders/$renderId/outputs/$outputId': typeof V1RendersRenderIdOutputsOutputIdRoute
  '/v1/studio/assets/$assetId/content': typeof V1StudioAssetsAssetIdContentRoute
  '/v1/studio/assets/$assetId/deletion-impact': typeof V1StudioAssetsAssetIdDeletionImpactRoute
  '/v1/studio/assets/$assetId/derivation-provenance': typeof V1StudioAssetsAssetIdDerivationProvenanceRoute
  '/v1/studio/assets/$assetId/derivations': typeof V1StudioAssetsAssetIdDerivationsRoute
  '/v1/studio/assets/$assetId/used': typeof V1StudioAssetsAssetIdUsedRoute
  '/v1/studio/assets/local-promotions/$localAssetId': typeof V1StudioAssetsLocalPromotionsLocalAssetIdRoute
  '/v1/studio/assets/local-promotions/resolve': typeof V1StudioAssetsLocalPromotionsResolveRoute
  '/v1/studio/assets/upload-reservations/$reservationId': typeof V1StudioAssetsUploadReservationsReservationIdRoute
  '/v1/studio/library/collections/$collectionId': typeof V1StudioLibraryCollectionsCollectionIdRouteWithChildren
  '/v1/studio/media-derivations/$jobId/cancel': typeof V1StudioMediaDerivationsJobIdCancelRoute
  '/v1/studio/media-derivations/$jobId/retry': typeof V1StudioMediaDerivationsJobIdRetryRoute
  '/v1/studio/assets/local-promotions': typeof V1StudioAssetsLocalPromotionsIndexRoute
  '/v1/studio/assets/upload-reservations': typeof V1StudioAssetsUploadReservationsIndexRoute
  '/v1/studio/library/collections': typeof V1StudioLibraryCollectionsIndexRoute
  '/v1/studio/library/items': typeof V1StudioLibraryItemsIndexRoute
  '/v1/studio/documents/$documentId/revisions/$snapshotId': typeof V1StudioDocumentsDocumentIdRevisionsSnapshotIdRoute
  '/v1/studio/library/collections/$collectionId/order': typeof V1StudioLibraryCollectionsCollectionIdOrderRoute
  '/v1/studio/library/items/$itemKind/$itemId/versions/$version': typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteWithChildren
  '/v1/studio/library/media/$assetId/versions/$version/content': typeof V1StudioLibraryMediaAssetIdVersionsVersionContentRoute
  '/v1/studio/library/items/$itemKind/$itemId/versions/$version/favorite': typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRoute
  '/v1/studio/library/items/$itemKind/$itemId/versions/$version/used': typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRoute
  '/v1/studio/library/collections/$collectionId/items/$itemKind/$itemId/versions/$version': typeof V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_studio': typeof StudioRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/render-conformance': typeof RenderConformanceRoute
  '/api/health': typeof ApiHealthRoute
  '/_studio/': typeof StudioIndexRoute
  '/_studio/composition-handoffs/$token': typeof StudioCompositionHandoffsTokenRoute
  '/_studio/documents/$documentId': typeof StudioDocumentsDocumentIdRoute
  '/v1/integrations/composition-handoffs': typeof V1IntegrationsCompositionHandoffsRoute
  '/v1/renders/$renderId': typeof V1RendersRenderIdRouteWithChildren
  '/v1/studio/export-pdf': typeof V1StudioExportPdfRoute
  '/v1/studio/export-png': typeof V1StudioExportPngRoute
  '/v1/studio/page-thumbnail': typeof V1StudioPageThumbnailRoute
  '/v1/studio/quotation-compositions': typeof V1StudioQuotationCompositionsRoute
  '/v1/studio/render': typeof V1StudioRenderRoute
  '/v1/studio/assets/$assetId': typeof V1StudioAssetsAssetIdRouteWithChildren
  '/v1/studio/composition-handoffs/$token': typeof V1StudioCompositionHandoffsTokenRoute
  '/v1/studio/figma-handoffs/$token': typeof V1StudioFigmaHandoffsTokenRoute
  '/v1/studio/library/preferences': typeof V1StudioLibraryPreferencesRoute
  '/v1/studio/media-derivations/$jobId': typeof V1StudioMediaDerivationsJobIdRouteWithChildren
  '/v1/studio/media-derivations/policy': typeof V1StudioMediaDerivationsPolicyRoute
  '/v1/studio/session/demo': typeof V1StudioSessionDemoRoute
  '/v1/studio/session/reset': typeof V1StudioSessionResetRoute
  '/v1/studio/session/token': typeof V1StudioSessionTokenRoute
  '/v1/studio/templates/$templateId': typeof V1StudioTemplatesTemplateIdRoute
  '/v1/studio/assets/': typeof V1StudioAssetsIndexRoute
  '/v1/studio/figma-handoffs/': typeof V1StudioFigmaHandoffsIndexRoute
  '/v1/studio/renders/': typeof V1StudioRendersIndexRoute
  '/v1/studio/templates/': typeof V1StudioTemplatesIndexRoute
  '/v1/renders/$renderId/outputs/$outputId': typeof V1RendersRenderIdOutputsOutputIdRoute
  '/v1/studio/assets/$assetId/content': typeof V1StudioAssetsAssetIdContentRoute
  '/v1/studio/assets/$assetId/deletion-impact': typeof V1StudioAssetsAssetIdDeletionImpactRoute
  '/v1/studio/assets/$assetId/derivation-provenance': typeof V1StudioAssetsAssetIdDerivationProvenanceRoute
  '/v1/studio/assets/$assetId/derivations': typeof V1StudioAssetsAssetIdDerivationsRoute
  '/v1/studio/assets/$assetId/used': typeof V1StudioAssetsAssetIdUsedRoute
  '/v1/studio/assets/local-promotions/$localAssetId': typeof V1StudioAssetsLocalPromotionsLocalAssetIdRoute
  '/v1/studio/assets/local-promotions/resolve': typeof V1StudioAssetsLocalPromotionsResolveRoute
  '/v1/studio/assets/upload-reservations/$reservationId': typeof V1StudioAssetsUploadReservationsReservationIdRoute
  '/v1/studio/library/collections/$collectionId': typeof V1StudioLibraryCollectionsCollectionIdRouteWithChildren
  '/v1/studio/media-derivations/$jobId/cancel': typeof V1StudioMediaDerivationsJobIdCancelRoute
  '/v1/studio/media-derivations/$jobId/retry': typeof V1StudioMediaDerivationsJobIdRetryRoute
  '/v1/studio/assets/local-promotions/': typeof V1StudioAssetsLocalPromotionsIndexRoute
  '/v1/studio/assets/upload-reservations/': typeof V1StudioAssetsUploadReservationsIndexRoute
  '/v1/studio/library/collections/': typeof V1StudioLibraryCollectionsIndexRoute
  '/v1/studio/library/items/': typeof V1StudioLibraryItemsIndexRoute
  '/v1/studio/documents/$documentId/revisions/$snapshotId': typeof V1StudioDocumentsDocumentIdRevisionsSnapshotIdRoute
  '/v1/studio/library/collections/$collectionId/order': typeof V1StudioLibraryCollectionsCollectionIdOrderRoute
  '/v1/studio/library/items/$itemKind/$itemId/versions/$version': typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteWithChildren
  '/v1/studio/library/media/$assetId/versions/$version/content': typeof V1StudioLibraryMediaAssetIdVersionsVersionContentRoute
  '/v1/studio/library/items/$itemKind/$itemId/versions/$version/favorite': typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRoute
  '/v1/studio/library/items/$itemKind/$itemId/versions/$version/used': typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRoute
  '/v1/studio/library/collections/$collectionId/items/$itemKind/$itemId/versions/$version': typeof V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/render-conformance'
    | '/api/health'
    | '/composition-handoffs/$token'
    | '/documents/$documentId'
    | '/v1/integrations/composition-handoffs'
    | '/v1/renders/$renderId'
    | '/v1/studio/export-pdf'
    | '/v1/studio/export-png'
    | '/v1/studio/page-thumbnail'
    | '/v1/studio/quotation-compositions'
    | '/v1/studio/render'
    | '/v1/studio/assets/$assetId'
    | '/v1/studio/composition-handoffs/$token'
    | '/v1/studio/figma-handoffs/$token'
    | '/v1/studio/library/preferences'
    | '/v1/studio/media-derivations/$jobId'
    | '/v1/studio/media-derivations/policy'
    | '/v1/studio/session/demo'
    | '/v1/studio/session/reset'
    | '/v1/studio/session/token'
    | '/v1/studio/templates/$templateId'
    | '/v1/studio/assets/'
    | '/v1/studio/figma-handoffs/'
    | '/v1/studio/renders/'
    | '/v1/studio/templates/'
    | '/v1/renders/$renderId/outputs/$outputId'
    | '/v1/studio/assets/$assetId/content'
    | '/v1/studio/assets/$assetId/deletion-impact'
    | '/v1/studio/assets/$assetId/derivation-provenance'
    | '/v1/studio/assets/$assetId/derivations'
    | '/v1/studio/assets/$assetId/used'
    | '/v1/studio/assets/local-promotions/$localAssetId'
    | '/v1/studio/assets/local-promotions/resolve'
    | '/v1/studio/assets/upload-reservations/$reservationId'
    | '/v1/studio/library/collections/$collectionId'
    | '/v1/studio/media-derivations/$jobId/cancel'
    | '/v1/studio/media-derivations/$jobId/retry'
    | '/v1/studio/assets/local-promotions/'
    | '/v1/studio/assets/upload-reservations/'
    | '/v1/studio/library/collections/'
    | '/v1/studio/library/items/'
    | '/v1/studio/documents/$documentId/revisions/$snapshotId'
    | '/v1/studio/library/collections/$collectionId/order'
    | '/v1/studio/library/items/$itemKind/$itemId/versions/$version'
    | '/v1/studio/library/media/$assetId/versions/$version/content'
    | '/v1/studio/library/items/$itemKind/$itemId/versions/$version/favorite'
    | '/v1/studio/library/items/$itemKind/$itemId/versions/$version/used'
    | '/v1/studio/library/collections/$collectionId/items/$itemKind/$itemId/versions/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/demo'
    | '/render-conformance'
    | '/api/health'
    | '/'
    | '/composition-handoffs/$token'
    | '/documents/$documentId'
    | '/v1/integrations/composition-handoffs'
    | '/v1/renders/$renderId'
    | '/v1/studio/export-pdf'
    | '/v1/studio/export-png'
    | '/v1/studio/page-thumbnail'
    | '/v1/studio/quotation-compositions'
    | '/v1/studio/render'
    | '/v1/studio/assets/$assetId'
    | '/v1/studio/composition-handoffs/$token'
    | '/v1/studio/figma-handoffs/$token'
    | '/v1/studio/library/preferences'
    | '/v1/studio/media-derivations/$jobId'
    | '/v1/studio/media-derivations/policy'
    | '/v1/studio/session/demo'
    | '/v1/studio/session/reset'
    | '/v1/studio/session/token'
    | '/v1/studio/templates/$templateId'
    | '/v1/studio/assets'
    | '/v1/studio/figma-handoffs'
    | '/v1/studio/renders'
    | '/v1/studio/templates'
    | '/v1/renders/$renderId/outputs/$outputId'
    | '/v1/studio/assets/$assetId/content'
    | '/v1/studio/assets/$assetId/deletion-impact'
    | '/v1/studio/assets/$assetId/derivation-provenance'
    | '/v1/studio/assets/$assetId/derivations'
    | '/v1/studio/assets/$assetId/used'
    | '/v1/studio/assets/local-promotions/$localAssetId'
    | '/v1/studio/assets/local-promotions/resolve'
    | '/v1/studio/assets/upload-reservations/$reservationId'
    | '/v1/studio/library/collections/$collectionId'
    | '/v1/studio/media-derivations/$jobId/cancel'
    | '/v1/studio/media-derivations/$jobId/retry'
    | '/v1/studio/assets/local-promotions'
    | '/v1/studio/assets/upload-reservations'
    | '/v1/studio/library/collections'
    | '/v1/studio/library/items'
    | '/v1/studio/documents/$documentId/revisions/$snapshotId'
    | '/v1/studio/library/collections/$collectionId/order'
    | '/v1/studio/library/items/$itemKind/$itemId/versions/$version'
    | '/v1/studio/library/media/$assetId/versions/$version/content'
    | '/v1/studio/library/items/$itemKind/$itemId/versions/$version/favorite'
    | '/v1/studio/library/items/$itemKind/$itemId/versions/$version/used'
    | '/v1/studio/library/collections/$collectionId/items/$itemKind/$itemId/versions/$version'
  id:
    | '__root__'
    | '/_studio'
    | '/demo'
    | '/render-conformance'
    | '/api/health'
    | '/_studio/'
    | '/_studio/composition-handoffs/$token'
    | '/_studio/documents/$documentId'
    | '/v1/integrations/composition-handoffs'
    | '/v1/renders/$renderId'
    | '/v1/studio/export-pdf'
    | '/v1/studio/export-png'
    | '/v1/studio/page-thumbnail'
    | '/v1/studio/quotation-compositions'
    | '/v1/studio/render'
    | '/v1/studio/assets/$assetId'
    | '/v1/studio/composition-handoffs/$token'
    | '/v1/studio/figma-handoffs/$token'
    | '/v1/studio/library/preferences'
    | '/v1/studio/media-derivations/$jobId'
    | '/v1/studio/media-derivations/policy'
    | '/v1/studio/session/demo'
    | '/v1/studio/session/reset'
    | '/v1/studio/session/token'
    | '/v1/studio/templates/$templateId'
    | '/v1/studio/assets/'
    | '/v1/studio/figma-handoffs/'
    | '/v1/studio/renders/'
    | '/v1/studio/templates/'
    | '/v1/renders/$renderId/outputs/$outputId'
    | '/v1/studio/assets/$assetId/content'
    | '/v1/studio/assets/$assetId/deletion-impact'
    | '/v1/studio/assets/$assetId/derivation-provenance'
    | '/v1/studio/assets/$assetId/derivations'
    | '/v1/studio/assets/$assetId/used'
    | '/v1/studio/assets/local-promotions/$localAssetId'
    | '/v1/studio/assets/local-promotions/resolve'
    | '/v1/studio/assets/upload-reservations/$reservationId'
    | '/v1/studio/library/collections/$collectionId'
    | '/v1/studio/media-derivations/$jobId/cancel'
    | '/v1/studio/media-derivations/$jobId/retry'
    | '/v1/studio/assets/local-promotions/'
    | '/v1/studio/assets/upload-reservations/'
    | '/v1/studio/library/collections/'
    | '/v1/studio/library/items/'
    | '/v1/studio/documents/$documentId/revisions/$snapshotId'
    | '/v1/studio/library/collections/$collectionId/order'
    | '/v1/studio/library/items/$itemKind/$itemId/versions/$version'
    | '/v1/studio/library/media/$assetId/versions/$version/content'
    | '/v1/studio/library/items/$itemKind/$itemId/versions/$version/favorite'
    | '/v1/studio/library/items/$itemKind/$itemId/versions/$version/used'
    | '/v1/studio/library/collections/$collectionId/items/$itemKind/$itemId/versions/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  RenderConformanceRoute: typeof RenderConformanceRoute
  ApiHealthRoute: typeof ApiHealthRoute
  V1IntegrationsCompositionHandoffsRoute: typeof V1IntegrationsCompositionHandoffsRoute
  V1RendersRenderIdRoute: typeof V1RendersRenderIdRouteWithChildren
  V1StudioExportPdfRoute: typeof V1StudioExportPdfRoute
  V1StudioExportPngRoute: typeof V1StudioExportPngRoute
  V1StudioPageThumbnailRoute: typeof V1StudioPageThumbnailRoute
  V1StudioQuotationCompositionsRoute: typeof V1StudioQuotationCompositionsRoute
  V1StudioRenderRoute: typeof V1StudioRenderRoute
  V1StudioAssetsAssetIdRoute: typeof V1StudioAssetsAssetIdRouteWithChildren
  V1StudioCompositionHandoffsTokenRoute: typeof V1StudioCompositionHandoffsTokenRoute
  V1StudioFigmaHandoffsTokenRoute: typeof V1StudioFigmaHandoffsTokenRoute
  V1StudioLibraryPreferencesRoute: typeof V1StudioLibraryPreferencesRoute
  V1StudioMediaDerivationsJobIdRoute: typeof V1StudioMediaDerivationsJobIdRouteWithChildren
  V1StudioMediaDerivationsPolicyRoute: typeof V1StudioMediaDerivationsPolicyRoute
  V1StudioSessionDemoRoute: typeof V1StudioSessionDemoRoute
  V1StudioSessionResetRoute: typeof V1StudioSessionResetRoute
  V1StudioSessionTokenRoute: typeof V1StudioSessionTokenRoute
  V1StudioTemplatesTemplateIdRoute: typeof V1StudioTemplatesTemplateIdRoute
  V1StudioAssetsIndexRoute: typeof V1StudioAssetsIndexRoute
  V1StudioFigmaHandoffsIndexRoute: typeof V1StudioFigmaHandoffsIndexRoute
  V1StudioRendersIndexRoute: typeof V1StudioRendersIndexRoute
  V1StudioTemplatesIndexRoute: typeof V1StudioTemplatesIndexRoute
  V1StudioAssetsLocalPromotionsLocalAssetIdRoute: typeof V1StudioAssetsLocalPromotionsLocalAssetIdRoute
  V1StudioAssetsLocalPromotionsResolveRoute: typeof V1StudioAssetsLocalPromotionsResolveRoute
  V1StudioAssetsUploadReservationsReservationIdRoute: typeof V1StudioAssetsUploadReservationsReservationIdRoute
  V1StudioLibraryCollectionsCollectionIdRoute: typeof V1StudioLibraryCollectionsCollectionIdRouteWithChildren
  V1StudioAssetsLocalPromotionsIndexRoute: typeof V1StudioAssetsLocalPromotionsIndexRoute
  V1StudioAssetsUploadReservationsIndexRoute: typeof V1StudioAssetsUploadReservationsIndexRoute
  V1StudioLibraryCollectionsIndexRoute: typeof V1StudioLibraryCollectionsIndexRoute
  V1StudioLibraryItemsIndexRoute: typeof V1StudioLibraryItemsIndexRoute
  V1StudioDocumentsDocumentIdRevisionsSnapshotIdRoute: typeof V1StudioDocumentsDocumentIdRevisionsSnapshotIdRoute
  V1StudioLibraryItemsItemKindItemIdVersionsVersionRoute: typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteWithChildren
  V1StudioLibraryMediaAssetIdVersionsVersionContentRoute: typeof V1StudioLibraryMediaAssetIdVersionsVersionContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render-conformance': {
      id: '/render-conformance'
      path: '/render-conformance'
      fullPath: '/render-conformance'
      preLoaderRoute: typeof RenderConformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/': {
      id: '/_studio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/composition-handoffs/$token': {
      id: '/_studio/composition-handoffs/$token'
      path: '/composition-handoffs/$token'
      fullPath: '/composition-handoffs/$token'
      preLoaderRoute: typeof StudioCompositionHandoffsTokenRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/_studio/documents/$documentId': {
      id: '/_studio/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof StudioDocumentsDocumentIdRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/v1/integrations/composition-handoffs': {
      id: '/v1/integrations/composition-handoffs'
      path: '/v1/integrations/composition-handoffs'
      fullPath: '/v1/integrations/composition-handoffs'
      preLoaderRoute: typeof V1IntegrationsCompositionHandoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/renders/$renderId': {
      id: '/v1/renders/$renderId'
      path: '/v1/renders/$renderId'
      fullPath: '/v1/renders/$renderId'
      preLoaderRoute: typeof V1RendersRenderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/export-pdf': {
      id: '/v1/studio/export-pdf'
      path: '/v1/studio/export-pdf'
      fullPath: '/v1/studio/export-pdf'
      preLoaderRoute: typeof V1StudioExportPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/export-png': {
      id: '/v1/studio/export-png'
      path: '/v1/studio/export-png'
      fullPath: '/v1/studio/export-png'
      preLoaderRoute: typeof V1StudioExportPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/page-thumbnail': {
      id: '/v1/studio/page-thumbnail'
      path: '/v1/studio/page-thumbnail'
      fullPath: '/v1/studio/page-thumbnail'
      preLoaderRoute: typeof V1StudioPageThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/quotation-compositions': {
      id: '/v1/studio/quotation-compositions'
      path: '/v1/studio/quotation-compositions'
      fullPath: '/v1/studio/quotation-compositions'
      preLoaderRoute: typeof V1StudioQuotationCompositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/render': {
      id: '/v1/studio/render'
      path: '/v1/studio/render'
      fullPath: '/v1/studio/render'
      preLoaderRoute: typeof V1StudioRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/assets/': {
      id: '/v1/studio/assets/'
      path: '/v1/studio/assets'
      fullPath: '/v1/studio/assets/'
      preLoaderRoute: typeof V1StudioAssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/assets/$assetId': {
      id: '/v1/studio/assets/$assetId'
      path: '/v1/studio/assets/$assetId'
      fullPath: '/v1/studio/assets/$assetId'
      preLoaderRoute: typeof V1StudioAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/composition-handoffs/$token': {
      id: '/v1/studio/composition-handoffs/$token'
      path: '/v1/studio/composition-handoffs/$token'
      fullPath: '/v1/studio/composition-handoffs/$token'
      preLoaderRoute: typeof V1StudioCompositionHandoffsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/figma-handoffs/': {
      id: '/v1/studio/figma-handoffs/'
      path: '/v1/studio/figma-handoffs'
      fullPath: '/v1/studio/figma-handoffs/'
      preLoaderRoute: typeof V1StudioFigmaHandoffsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/figma-handoffs/$token': {
      id: '/v1/studio/figma-handoffs/$token'
      path: '/v1/studio/figma-handoffs/$token'
      fullPath: '/v1/studio/figma-handoffs/$token'
      preLoaderRoute: typeof V1StudioFigmaHandoffsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/library/preferences': {
      id: '/v1/studio/library/preferences'
      path: '/v1/studio/library/preferences'
      fullPath: '/v1/studio/library/preferences'
      preLoaderRoute: typeof V1StudioLibraryPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/media-derivations/$jobId': {
      id: '/v1/studio/media-derivations/$jobId'
      path: '/v1/studio/media-derivations/$jobId'
      fullPath: '/v1/studio/media-derivations/$jobId'
      preLoaderRoute: typeof V1StudioMediaDerivationsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/media-derivations/policy': {
      id: '/v1/studio/media-derivations/policy'
      path: '/v1/studio/media-derivations/policy'
      fullPath: '/v1/studio/media-derivations/policy'
      preLoaderRoute: typeof V1StudioMediaDerivationsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/renders/': {
      id: '/v1/studio/renders/'
      path: '/v1/studio/renders'
      fullPath: '/v1/studio/renders/'
      preLoaderRoute: typeof V1StudioRendersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/session/demo': {
      id: '/v1/studio/session/demo'
      path: '/v1/studio/session/demo'
      fullPath: '/v1/studio/session/demo'
      preLoaderRoute: typeof V1StudioSessionDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/session/reset': {
      id: '/v1/studio/session/reset'
      path: '/v1/studio/session/reset'
      fullPath: '/v1/studio/session/reset'
      preLoaderRoute: typeof V1StudioSessionResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/session/token': {
      id: '/v1/studio/session/token'
      path: '/v1/studio/session/token'
      fullPath: '/v1/studio/session/token'
      preLoaderRoute: typeof V1StudioSessionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/templates/': {
      id: '/v1/studio/templates/'
      path: '/v1/studio/templates'
      fullPath: '/v1/studio/templates/'
      preLoaderRoute: typeof V1StudioTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/templates/$templateId': {
      id: '/v1/studio/templates/$templateId'
      path: '/v1/studio/templates/$templateId'
      fullPath: '/v1/studio/templates/$templateId'
      preLoaderRoute: typeof V1StudioTemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/renders/$renderId/outputs/$outputId': {
      id: '/v1/renders/$renderId/outputs/$outputId'
      path: '/outputs/$outputId'
      fullPath: '/v1/renders/$renderId/outputs/$outputId'
      preLoaderRoute: typeof V1RendersRenderIdOutputsOutputIdRouteImport
      parentRoute: typeof V1RendersRenderIdRoute
    }
    '/v1/studio/assets/$assetId/content': {
      id: '/v1/studio/assets/$assetId/content'
      path: '/content'
      fullPath: '/v1/studio/assets/$assetId/content'
      preLoaderRoute: typeof V1StudioAssetsAssetIdContentRouteImport
      parentRoute: typeof V1StudioAssetsAssetIdRoute
    }
    '/v1/studio/assets/$assetId/deletion-impact': {
      id: '/v1/studio/assets/$assetId/deletion-impact'
      path: '/deletion-impact'
      fullPath: '/v1/studio/assets/$assetId/deletion-impact'
      preLoaderRoute: typeof V1StudioAssetsAssetIdDeletionImpactRouteImport
      parentRoute: typeof V1StudioAssetsAssetIdRoute
    }
    '/v1/studio/assets/$assetId/derivation-provenance': {
      id: '/v1/studio/assets/$assetId/derivation-provenance'
      path: '/derivation-provenance'
      fullPath: '/v1/studio/assets/$assetId/derivation-provenance'
      preLoaderRoute: typeof V1StudioAssetsAssetIdDerivationProvenanceRouteImport
      parentRoute: typeof V1StudioAssetsAssetIdRoute
    }
    '/v1/studio/assets/$assetId/derivations': {
      id: '/v1/studio/assets/$assetId/derivations'
      path: '/derivations'
      fullPath: '/v1/studio/assets/$assetId/derivations'
      preLoaderRoute: typeof V1StudioAssetsAssetIdDerivationsRouteImport
      parentRoute: typeof V1StudioAssetsAssetIdRoute
    }
    '/v1/studio/assets/$assetId/used': {
      id: '/v1/studio/assets/$assetId/used'
      path: '/used'
      fullPath: '/v1/studio/assets/$assetId/used'
      preLoaderRoute: typeof V1StudioAssetsAssetIdUsedRouteImport
      parentRoute: typeof V1StudioAssetsAssetIdRoute
    }
    '/v1/studio/assets/local-promotions/': {
      id: '/v1/studio/assets/local-promotions/'
      path: '/v1/studio/assets/local-promotions'
      fullPath: '/v1/studio/assets/local-promotions/'
      preLoaderRoute: typeof V1StudioAssetsLocalPromotionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/assets/local-promotions/$localAssetId': {
      id: '/v1/studio/assets/local-promotions/$localAssetId'
      path: '/v1/studio/assets/local-promotions/$localAssetId'
      fullPath: '/v1/studio/assets/local-promotions/$localAssetId'
      preLoaderRoute: typeof V1StudioAssetsLocalPromotionsLocalAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/assets/local-promotions/resolve': {
      id: '/v1/studio/assets/local-promotions/resolve'
      path: '/v1/studio/assets/local-promotions/resolve'
      fullPath: '/v1/studio/assets/local-promotions/resolve'
      preLoaderRoute: typeof V1StudioAssetsLocalPromotionsResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/assets/upload-reservations/': {
      id: '/v1/studio/assets/upload-reservations/'
      path: '/v1/studio/assets/upload-reservations'
      fullPath: '/v1/studio/assets/upload-reservations/'
      preLoaderRoute: typeof V1StudioAssetsUploadReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/assets/upload-reservations/$reservationId': {
      id: '/v1/studio/assets/upload-reservations/$reservationId'
      path: '/v1/studio/assets/upload-reservations/$reservationId'
      fullPath: '/v1/studio/assets/upload-reservations/$reservationId'
      preLoaderRoute: typeof V1StudioAssetsUploadReservationsReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/library/collections/': {
      id: '/v1/studio/library/collections/'
      path: '/v1/studio/library/collections'
      fullPath: '/v1/studio/library/collections/'
      preLoaderRoute: typeof V1StudioLibraryCollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/library/collections/$collectionId': {
      id: '/v1/studio/library/collections/$collectionId'
      path: '/v1/studio/library/collections/$collectionId'
      fullPath: '/v1/studio/library/collections/$collectionId'
      preLoaderRoute: typeof V1StudioLibraryCollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/library/items/': {
      id: '/v1/studio/library/items/'
      path: '/v1/studio/library/items'
      fullPath: '/v1/studio/library/items/'
      preLoaderRoute: typeof V1StudioLibraryItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/media-derivations/$jobId/cancel': {
      id: '/v1/studio/media-derivations/$jobId/cancel'
      path: '/cancel'
      fullPath: '/v1/studio/media-derivations/$jobId/cancel'
      preLoaderRoute: typeof V1StudioMediaDerivationsJobIdCancelRouteImport
      parentRoute: typeof V1StudioMediaDerivationsJobIdRoute
    }
    '/v1/studio/media-derivations/$jobId/retry': {
      id: '/v1/studio/media-derivations/$jobId/retry'
      path: '/retry'
      fullPath: '/v1/studio/media-derivations/$jobId/retry'
      preLoaderRoute: typeof V1StudioMediaDerivationsJobIdRetryRouteImport
      parentRoute: typeof V1StudioMediaDerivationsJobIdRoute
    }
    '/v1/studio/documents/$documentId/revisions/$snapshotId': {
      id: '/v1/studio/documents/$documentId/revisions/$snapshotId'
      path: '/v1/studio/documents/$documentId/revisions/$snapshotId'
      fullPath: '/v1/studio/documents/$documentId/revisions/$snapshotId'
      preLoaderRoute: typeof V1StudioDocumentsDocumentIdRevisionsSnapshotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/library/collections/$collectionId/order': {
      id: '/v1/studio/library/collections/$collectionId/order'
      path: '/order'
      fullPath: '/v1/studio/library/collections/$collectionId/order'
      preLoaderRoute: typeof V1StudioLibraryCollectionsCollectionIdOrderRouteImport
      parentRoute: typeof V1StudioLibraryCollectionsCollectionIdRoute
    }
    '/v1/studio/library/items/$itemKind/$itemId/versions/$version': {
      id: '/v1/studio/library/items/$itemKind/$itemId/versions/$version'
      path: '/v1/studio/library/items/$itemKind/$itemId/versions/$version'
      fullPath: '/v1/studio/library/items/$itemKind/$itemId/versions/$version'
      preLoaderRoute: typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/library/media/$assetId/versions/$version/content': {
      id: '/v1/studio/library/media/$assetId/versions/$version/content'
      path: '/v1/studio/library/media/$assetId/versions/$version/content'
      fullPath: '/v1/studio/library/media/$assetId/versions/$version/content'
      preLoaderRoute: typeof V1StudioLibraryMediaAssetIdVersionsVersionContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/library/items/$itemKind/$itemId/versions/$version/favorite': {
      id: '/v1/studio/library/items/$itemKind/$itemId/versions/$version/favorite'
      path: '/favorite'
      fullPath: '/v1/studio/library/items/$itemKind/$itemId/versions/$version/favorite'
      preLoaderRoute: typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRouteImport
      parentRoute: typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionRoute
    }
    '/v1/studio/library/items/$itemKind/$itemId/versions/$version/used': {
      id: '/v1/studio/library/items/$itemKind/$itemId/versions/$version/used'
      path: '/used'
      fullPath: '/v1/studio/library/items/$itemKind/$itemId/versions/$version/used'
      preLoaderRoute: typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRouteImport
      parentRoute: typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionRoute
    }
    '/v1/studio/library/collections/$collectionId/items/$itemKind/$itemId/versions/$version': {
      id: '/v1/studio/library/collections/$collectionId/items/$itemKind/$itemId/versions/$version'
      path: '/items/$itemKind/$itemId/versions/$version'
      fullPath: '/v1/studio/library/collections/$collectionId/items/$itemKind/$itemId/versions/$version'
      preLoaderRoute: typeof V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRouteImport
      parentRoute: typeof V1StudioLibraryCollectionsCollectionIdRoute
    }
  }
}

interface StudioRouteRouteChildren {
  StudioIndexRoute: typeof StudioIndexRoute
  StudioCompositionHandoffsTokenRoute: typeof StudioCompositionHandoffsTokenRoute
  StudioDocumentsDocumentIdRoute: typeof StudioDocumentsDocumentIdRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioIndexRoute: StudioIndexRoute,
  StudioCompositionHandoffsTokenRoute: StudioCompositionHandoffsTokenRoute,
  StudioDocumentsDocumentIdRoute: StudioDocumentsDocumentIdRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

interface V1RendersRenderIdRouteChildren {
  V1RendersRenderIdOutputsOutputIdRoute: typeof V1RendersRenderIdOutputsOutputIdRoute
}

const V1RendersRenderIdRouteChildren: V1RendersRenderIdRouteChildren = {
  V1RendersRenderIdOutputsOutputIdRoute: V1RendersRenderIdOutputsOutputIdRoute,
}

const V1RendersRenderIdRouteWithChildren =
  V1RendersRenderIdRoute._addFileChildren(V1RendersRenderIdRouteChildren)

interface V1StudioAssetsAssetIdRouteChildren {
  V1StudioAssetsAssetIdContentRoute: typeof V1StudioAssetsAssetIdContentRoute
  V1StudioAssetsAssetIdDeletionImpactRoute: typeof V1StudioAssetsAssetIdDeletionImpactRoute
  V1StudioAssetsAssetIdDerivationProvenanceRoute: typeof V1StudioAssetsAssetIdDerivationProvenanceRoute
  V1StudioAssetsAssetIdDerivationsRoute: typeof V1StudioAssetsAssetIdDerivationsRoute
  V1StudioAssetsAssetIdUsedRoute: typeof V1StudioAssetsAssetIdUsedRoute
}

const V1StudioAssetsAssetIdRouteChildren: V1StudioAssetsAssetIdRouteChildren = {
  V1StudioAssetsAssetIdContentRoute: V1StudioAssetsAssetIdContentRoute,
  V1StudioAssetsAssetIdDeletionImpactRoute:
    V1StudioAssetsAssetIdDeletionImpactRoute,
  V1StudioAssetsAssetIdDerivationProvenanceRoute:
    V1StudioAssetsAssetIdDerivationProvenanceRoute,
  V1StudioAssetsAssetIdDerivationsRoute: V1StudioAssetsAssetIdDerivationsRoute,
  V1StudioAssetsAssetIdUsedRoute: V1StudioAssetsAssetIdUsedRoute,
}

const V1StudioAssetsAssetIdRouteWithChildren =
  V1StudioAssetsAssetIdRoute._addFileChildren(
    V1StudioAssetsAssetIdRouteChildren,
  )

interface V1StudioMediaDerivationsJobIdRouteChildren {
  V1StudioMediaDerivationsJobIdCancelRoute: typeof V1StudioMediaDerivationsJobIdCancelRoute
  V1StudioMediaDerivationsJobIdRetryRoute: typeof V1StudioMediaDerivationsJobIdRetryRoute
}

const V1StudioMediaDerivationsJobIdRouteChildren: V1StudioMediaDerivationsJobIdRouteChildren =
  {
    V1StudioMediaDerivationsJobIdCancelRoute:
      V1StudioMediaDerivationsJobIdCancelRoute,
    V1StudioMediaDerivationsJobIdRetryRoute:
      V1StudioMediaDerivationsJobIdRetryRoute,
  }

const V1StudioMediaDerivationsJobIdRouteWithChildren =
  V1StudioMediaDerivationsJobIdRoute._addFileChildren(
    V1StudioMediaDerivationsJobIdRouteChildren,
  )

interface V1StudioLibraryCollectionsCollectionIdRouteChildren {
  V1StudioLibraryCollectionsCollectionIdOrderRoute: typeof V1StudioLibraryCollectionsCollectionIdOrderRoute
  V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRoute: typeof V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRoute
}

const V1StudioLibraryCollectionsCollectionIdRouteChildren: V1StudioLibraryCollectionsCollectionIdRouteChildren =
  {
    V1StudioLibraryCollectionsCollectionIdOrderRoute:
      V1StudioLibraryCollectionsCollectionIdOrderRoute,
    V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRoute:
      V1StudioLibraryCollectionsCollectionIdItemsItemKindItemIdVersionsVersionRoute,
  }

const V1StudioLibraryCollectionsCollectionIdRouteWithChildren =
  V1StudioLibraryCollectionsCollectionIdRoute._addFileChildren(
    V1StudioLibraryCollectionsCollectionIdRouteChildren,
  )

interface V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteChildren {
  V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRoute: typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRoute
  V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRoute: typeof V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRoute
}

const V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteChildren: V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteChildren =
  {
    V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRoute:
      V1StudioLibraryItemsItemKindItemIdVersionsVersionFavoriteRoute,
    V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRoute:
      V1StudioLibraryItemsItemKindItemIdVersionsVersionUsedRoute,
  }

const V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteWithChildren =
  V1StudioLibraryItemsItemKindItemIdVersionsVersionRoute._addFileChildren(
    V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  StudioRouteRoute: StudioRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  RenderConformanceRoute: RenderConformanceRoute,
  ApiHealthRoute: ApiHealthRoute,
  V1IntegrationsCompositionHandoffsRoute:
    V1IntegrationsCompositionHandoffsRoute,
  V1RendersRenderIdRoute: V1RendersRenderIdRouteWithChildren,
  V1StudioExportPdfRoute: V1StudioExportPdfRoute,
  V1StudioExportPngRoute: V1StudioExportPngRoute,
  V1StudioPageThumbnailRoute: V1StudioPageThumbnailRoute,
  V1StudioQuotationCompositionsRoute: V1StudioQuotationCompositionsRoute,
  V1StudioRenderRoute: V1StudioRenderRoute,
  V1StudioAssetsAssetIdRoute: V1StudioAssetsAssetIdRouteWithChildren,
  V1StudioCompositionHandoffsTokenRoute: V1StudioCompositionHandoffsTokenRoute,
  V1StudioFigmaHandoffsTokenRoute: V1StudioFigmaHandoffsTokenRoute,
  V1StudioLibraryPreferencesRoute: V1StudioLibraryPreferencesRoute,
  V1StudioMediaDerivationsJobIdRoute:
    V1StudioMediaDerivationsJobIdRouteWithChildren,
  V1StudioMediaDerivationsPolicyRoute: V1StudioMediaDerivationsPolicyRoute,
  V1StudioSessionDemoRoute: V1StudioSessionDemoRoute,
  V1StudioSessionResetRoute: V1StudioSessionResetRoute,
  V1StudioSessionTokenRoute: V1StudioSessionTokenRoute,
  V1StudioTemplatesTemplateIdRoute: V1StudioTemplatesTemplateIdRoute,
  V1StudioAssetsIndexRoute: V1StudioAssetsIndexRoute,
  V1StudioFigmaHandoffsIndexRoute: V1StudioFigmaHandoffsIndexRoute,
  V1StudioRendersIndexRoute: V1StudioRendersIndexRoute,
  V1StudioTemplatesIndexRoute: V1StudioTemplatesIndexRoute,
  V1StudioAssetsLocalPromotionsLocalAssetIdRoute:
    V1StudioAssetsLocalPromotionsLocalAssetIdRoute,
  V1StudioAssetsLocalPromotionsResolveRoute:
    V1StudioAssetsLocalPromotionsResolveRoute,
  V1StudioAssetsUploadReservationsReservationIdRoute:
    V1StudioAssetsUploadReservationsReservationIdRoute,
  V1StudioLibraryCollectionsCollectionIdRoute:
    V1StudioLibraryCollectionsCollectionIdRouteWithChildren,
  V1StudioAssetsLocalPromotionsIndexRoute:
    V1StudioAssetsLocalPromotionsIndexRoute,
  V1StudioAssetsUploadReservationsIndexRoute:
    V1StudioAssetsUploadReservationsIndexRoute,
  V1StudioLibraryCollectionsIndexRoute: V1StudioLibraryCollectionsIndexRoute,
  V1StudioLibraryItemsIndexRoute: V1StudioLibraryItemsIndexRoute,
  V1StudioDocumentsDocumentIdRevisionsSnapshotIdRoute:
    V1StudioDocumentsDocumentIdRevisionsSnapshotIdRoute,
  V1StudioLibraryItemsItemKindItemIdVersionsVersionRoute:
    V1StudioLibraryItemsItemKindItemIdVersionsVersionRouteWithChildren,
  V1StudioLibraryMediaAssetIdVersionsVersionContentRoute:
    V1StudioLibraryMediaAssetIdVersionsVersionContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
