/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as V1RendersRenderIdRouteImport } from './routes/v1/renders/$renderId'
import { Route as V1StudioExportPdfRouteImport } from './routes/v1/studio/export-pdf'
import { Route as V1StudioExportPngRouteImport } from './routes/v1/studio/export-png'
import { Route as V1StudioRenderRouteImport } from './routes/v1/studio/render'
import { Route as V1StudioTemplatesIndexRouteImport } from './routes/v1/studio/templates/index'
import { Route as V1StudioTemplatesTemplateIdRouteImport } from './routes/v1/studio/templates/$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const V1RendersRenderIdRoute = V1RendersRenderIdRouteImport.update({
  id: '/v1/renders/$renderId',
  path: '/v1/renders/$renderId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioExportPdfRoute = V1StudioExportPdfRouteImport.update({
  id: '/v1/studio/export-pdf',
  path: '/v1/studio/export-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioExportPngRoute = V1StudioExportPngRouteImport.update({
  id: '/v1/studio/export-png',
  path: '/v1/studio/export-png',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioRenderRoute = V1StudioRenderRouteImport.update({
  id: '/v1/studio/render',
  path: '/v1/studio/render',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioTemplatesIndexRoute = V1StudioTemplatesIndexRouteImport.update({
  id: '/v1/studio/templates/',
  path: '/v1/studio/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StudioTemplatesTemplateIdRoute =
  V1StudioTemplatesTemplateIdRouteImport.update({
    id: '/v1/studio/templates/$templateId',
    path: '/v1/studio/templates/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/v1/renders/$renderId': typeof V1RendersRenderIdRoute
  '/v1/studio/export-pdf': typeof V1StudioExportPdfRoute
  '/v1/studio/export-png': typeof V1StudioExportPngRoute
  '/v1/studio/render': typeof V1StudioRenderRoute
  '/v1/studio/templates/$templateId': typeof V1StudioTemplatesTemplateIdRoute
  '/v1/studio/templates/': typeof V1StudioTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/v1/renders/$renderId': typeof V1RendersRenderIdRoute
  '/v1/studio/export-pdf': typeof V1StudioExportPdfRoute
  '/v1/studio/export-png': typeof V1StudioExportPngRoute
  '/v1/studio/render': typeof V1StudioRenderRoute
  '/v1/studio/templates/$templateId': typeof V1StudioTemplatesTemplateIdRoute
  '/v1/studio/templates': typeof V1StudioTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/v1/renders/$renderId': typeof V1RendersRenderIdRoute
  '/v1/studio/export-pdf': typeof V1StudioExportPdfRoute
  '/v1/studio/export-png': typeof V1StudioExportPngRoute
  '/v1/studio/render': typeof V1StudioRenderRoute
  '/v1/studio/templates/$templateId': typeof V1StudioTemplatesTemplateIdRoute
  '/v1/studio/templates/': typeof V1StudioTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/v1/renders/$renderId'
    | '/v1/studio/export-pdf'
    | '/v1/studio/export-png'
    | '/v1/studio/render'
    | '/v1/studio/templates/$templateId'
    | '/v1/studio/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/v1/renders/$renderId'
    | '/v1/studio/export-pdf'
    | '/v1/studio/export-png'
    | '/v1/studio/render'
    | '/v1/studio/templates/$templateId'
    | '/v1/studio/templates'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/v1/renders/$renderId'
    | '/v1/studio/export-pdf'
    | '/v1/studio/export-png'
    | '/v1/studio/render'
    | '/v1/studio/templates/$templateId'
    | '/v1/studio/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  V1RendersRenderIdRoute: typeof V1RendersRenderIdRoute
  V1StudioExportPdfRoute: typeof V1StudioExportPdfRoute
  V1StudioExportPngRoute: typeof V1StudioExportPngRoute
  V1StudioRenderRoute: typeof V1StudioRenderRoute
  V1StudioTemplatesTemplateIdRoute: typeof V1StudioTemplatesTemplateIdRoute
  V1StudioTemplatesIndexRoute: typeof V1StudioTemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/renders/$renderId': {
      id: '/v1/renders/$renderId'
      path: '/v1/renders/$renderId'
      fullPath: '/v1/renders/$renderId'
      preLoaderRoute: typeof V1RendersRenderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/export-pdf': {
      id: '/v1/studio/export-pdf'
      path: '/v1/studio/export-pdf'
      fullPath: '/v1/studio/export-pdf'
      preLoaderRoute: typeof V1StudioExportPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/export-png': {
      id: '/v1/studio/export-png'
      path: '/v1/studio/export-png'
      fullPath: '/v1/studio/export-png'
      preLoaderRoute: typeof V1StudioExportPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/render': {
      id: '/v1/studio/render'
      path: '/v1/studio/render'
      fullPath: '/v1/studio/render'
      preLoaderRoute: typeof V1StudioRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/templates/': {
      id: '/v1/studio/templates/'
      path: '/v1/studio/templates'
      fullPath: '/v1/studio/templates/'
      preLoaderRoute: typeof V1StudioTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/studio/templates/$templateId': {
      id: '/v1/studio/templates/$templateId'
      path: '/v1/studio/templates/$templateId'
      fullPath: '/v1/studio/templates/$templateId'
      preLoaderRoute: typeof V1StudioTemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  V1RendersRenderIdRoute: V1RendersRenderIdRoute,
  V1StudioExportPdfRoute: V1StudioExportPdfRoute,
  V1StudioExportPngRoute: V1StudioExportPngRoute,
  V1StudioRenderRoute: V1StudioRenderRoute,
  V1StudioTemplatesTemplateIdRoute: V1StudioTemplatesTemplateIdRoute,
  V1StudioTemplatesIndexRoute: V1StudioTemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
